# Generated by Django 4.0.2 on 2022-03-13 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=50, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=10, null=True)),
                ('district_id', models.IntegerField(null=True)),
                ('school_id', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100, null=True)),
                ('no_of_students', models.IntegerField()),
                ('no_of_girls', models.IntegerField()),
                ('no_of_boys', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user', verbose_name='the related User')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=200, null=True)),
                ('no_of_schools', models.IntegerField()),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.school', verbose_name='the related school')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user', verbose_name='the related User')),
            ],
        ),
    ]
