# Generated by Django 4.0.2 on 2022-03-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='user_id',
        ),
    ]
