# Generated by Django 4.0.2 on 2022-03-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_school_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='district',
            name='user_id',
        ),
    ]
