# Generated by Django 4.0.2 on 2022-03-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_district_add_school_district_add_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
